"""empty message

Revision ID: 1c5d721f1976
Revises: a819ed7b61f4
Create Date: 2025-01-29 11:06:21.284121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5d721f1976'
down_revision = 'a819ed7b61f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('meta_value',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.alter_column('meta_value',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('users')
    # ### end Alembic commands ###
